
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LIZBETHMB
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    ConsultasUsuarios cu;
    ConsultasEmpleados ce;
    ConsultasEmpleados cone;
    ConsultasUsuarios con;
    public Administrador() {
        initComponents();
       
        //Consultas Usuarios
        cu= new ConsultasUsuarios();
        ce= new ConsultasEmpleados();
        cone= new ConsultasEmpleados();
        con= new ConsultasUsuarios();
            
            con.MostrarTabla(tablaUsuarios);
            actualizar();
            
            
       
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblNombre1 = new javax.swing.JLabel();
        lblTipo1 = new javax.swing.JLabel();
        lblDomicilio1 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidosEmpleado = new javax.swing.JTextField();
        txtSalarioEmpleados = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTelefono2 = new javax.swing.JLabel();
        txtColoniaEmpleado = new javax.swing.JTextField();
        lblTelefono3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cmbCargoEmpleado = new javax.swing.JComboBox<>();
        lblDomicilio3 = new javax.swing.JLabel();
        txtCalleEmpleado = new javax.swing.JTextField();
        lblDomicilio4 = new javax.swing.JLabel();
        txtTelefonoEmpleados = new javax.swing.JTextField();
        lblDomicilio5 = new javax.swing.JLabel();
        lblDomicilio6 = new javax.swing.JLabel();
        txtNumEmpleados = new javax.swing.JTextField();
        txtMovilEmpleados = new javax.swing.JTextField();
        btnAddEmpleados = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnEliminar1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        lblNombre7 = new javax.swing.JLabel();
        txtEliminar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblDomicilio2 = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        lblDomicilio7 = new javax.swing.JLabel();
        lblDomicilio8 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        txtConfirmar = new javax.swing.JPasswordField();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        lblNombre3 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        lblNombre5 = new javax.swing.JLabel();
        lblNombre6 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(452, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(262, 262, 262))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton1)
                .addContainerGap(502, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 51));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setFocusTraversalPolicyProvider(true);
        jTabbedPane1.setInheritsPopupMenu(true);
        jTabbedPane1.setOpaque(true);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setDoubleBuffered(false);
        jPanel5.setEnabled(false);
        jPanel5.setFocusable(false);
        jPanel5.setOpaque(false);
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setVerifyInputWhenFocusTarget(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e41a17bc530e920fe173955f5d5de442.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 100, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TITULOINVENTARIO.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12345.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Inventario", new javax.swing.ImageIcon(getClass().getResource("/mas/InventarioIcon.png")), jPanel5); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 0, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(0, 0, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre1.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("ID");
        jPanel9.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, -1));

        lblTipo1.setBackground(new java.awt.Color(255, 255, 255));
        lblTipo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo1.setText("Cargo");
        jPanel9.add(lblTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        lblDomicilio1.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio1.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio1.setText("Contacto");
        jPanel9.add(lblDomicilio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Calle");
        jPanel9.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblNombre2.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre2.setText("Apellidos");
        jPanel9.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        txtNombreEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEmpleadoKeyTyped(evt);
            }
        });
        jPanel9.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, 28));

        txtApellidosEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosEmpleadoKeyTyped(evt);
            }
        });
        jPanel9.add(txtApellidosEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 150, 28));

        txtSalarioEmpleados.setText("$");
        jPanel9.add(txtSalarioEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 92, 28));
        jPanel9.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 610, 10));

        lblTelefono2.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefono2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefono2.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono2.setText("Colonia");
        jPanel9.add(lblTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        txtColoniaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColoniaEmpleadoActionPerformed(evt);
            }
        });
        txtColoniaEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColoniaEmpleadoKeyTyped(evt);
            }
        });
        jPanel9.add(txtColoniaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 150, 28));

        lblTelefono3.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefono3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefono3.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono3.setText(" # ");
        jPanel9.add(lblTelefono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));
        jPanel9.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 620, 10));

        cmbCargoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        cmbCargoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Encargado", "Vendedor", "Trabajador" }));
        jPanel9.add(cmbCargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        lblDomicilio3.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio3.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio3.setText("Domicilio");
        jPanel9.add(lblDomicilio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtCalleEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalleEmpleadoKeyTyped(evt);
            }
        });
        jPanel9.add(txtCalleEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, 28));

        lblDomicilio4.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio4.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio4.setText("Tel.Casa");
        jPanel9.add(lblDomicilio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel9.add(txtTelefonoEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 122, 28));

        lblDomicilio5.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio5.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio5.setText("Tel.Movil");
        jPanel9.add(lblDomicilio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        lblDomicilio6.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio6.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio6.setText("Salario");
        jPanel9.add(lblDomicilio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));
        jPanel9.add(txtNumEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 61, 28));
        jPanel9.add(txtMovilEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 121, 28));

        btnAddEmpleados.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddEmpleados.setForeground(new java.awt.Color(0, 0, 102));
        btnAddEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/AddUserBotton.png"))); // NOI18N
        btnAddEmpleados.setToolTipText("");
        btnAddEmpleados.setAlignmentY(0.0F);
        btnAddEmpleados.setBorder(null);
        btnAddEmpleados.setContentAreaFilled(false);
        btnAddEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddEmpleados.setDefaultCapable(false);
        btnAddEmpleados.setFocusPainted(false);
        btnAddEmpleados.setFocusable(false);
        btnAddEmpleados.setIconTextGap(10);
        btnAddEmpleados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/AddUserBottonPressed.png"))); // NOI18N
        btnAddEmpleados.setRequestFocusEnabled(false);
        btnAddEmpleados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/AddUserBottonSelected.png"))); // NOI18N
        btnAddEmpleados.setVerifyInputWhenFocusTarget(false);
        btnAddEmpleados.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpleadosActionPerformed(evt);
            }
        });
        jPanel9.add(btnAddEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 18, 90));

        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/Eliminar.png"))); // NOI18N
        btnEliminar1.setToolTipText("");
        btnEliminar1.setBorder(null);
        btnEliminar1.setBorderPainted(false);
        btnEliminar1.setContentAreaFilled(false);
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar1.setDefaultCapable(false);
        btnEliminar1.setFocusPainted(false);
        btnEliminar1.setFocusable(false);
        btnEliminar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/EliminarPressed.png"))); // NOI18N
        btnEliminar1.setRequestFocusEnabled(false);
        btnEliminar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/EliminarSeleted.png"))); // NOI18N
        btnEliminar1.setVerifyInputWhenFocusTarget(false);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel9.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        jPanel9.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 620, -1));

        lblNombre7.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre7.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre7.setText("Nombre");
        jPanel9.add(lblNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEliminarKeyTyped(evt);
            }
        });
        jPanel9.add(txtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 28));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 620, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e41a17bc530e920fe173955f5d5de442.png"))); // NOI18N
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 100, 130));

        TablaEmpleados.setBackground(new java.awt.Color(0, 153, 204));
        TablaEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", "", ""
            }
        ));
        TablaEmpleados.setGridColor(new java.awt.Color(0, 0, 51));
        TablaEmpleados.setSelectionBackground(new java.awt.Color(0, 0, 51));
        TablaEmpleados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaEmpleados);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 760, 140));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TITULOEMPLEADOS.png"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12345.png"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 660));

        jTabbedPane1.addTab("Empleados", new javax.swing.ImageIcon(getClass().getResource("/mas/empleados.png")), jPanel6); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Usuario");
        jPanel4.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblDomicilio.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio.setText("Contraseña");
        jPanel4.add(lblDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel4.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 150, 28));

        lblDomicilio2.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio2.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio2.setText("Tipo");
        jPanel4.add(lblDomicilio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        btnAddUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(0, 0, 102));
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/AddUserBotton.png"))); // NOI18N
        btnAddUser.setToolTipText("");
        btnAddUser.setAlignmentY(0.0F);
        btnAddUser.setBorder(null);
        btnAddUser.setContentAreaFilled(false);
        btnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddUser.setDefaultCapable(false);
        btnAddUser.setFocusPainted(false);
        btnAddUser.setFocusable(false);
        btnAddUser.setIconTextGap(10);
        btnAddUser.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/AddUserBottonPressed.png"))); // NOI18N
        btnAddUser.setRequestFocusEnabled(false);
        btnAddUser.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/AddUserBottonSelected.png"))); // NOI18N
        btnAddUser.setVerifyInputWhenFocusTarget(false);
        btnAddUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        lblDomicilio7.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio7.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio7.setText("ID_Empleado");
        jPanel4.add(lblDomicilio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        lblDomicilio8.setBackground(new java.awt.Color(255, 255, 255));
        lblDomicilio8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDomicilio8.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio8.setText("Confirmar");
        jPanel4.add(lblDomicilio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 150, 28));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));
        jPanel4.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        txtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmarActionPerformed(evt);
            }
        });
        jPanel4.add(txtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 150, 30));
        jPanel4.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 580, 200));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e41a17bc530e920fe173955f5d5de442.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 100, 130));

        tablaUsuarios.setAutoCreateRowSorter(true);
        tablaUsuarios.setBackground(new java.awt.Color(0, 0, 102));
        tablaUsuarios.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tablaUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Nombre", "Apellidos", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tablaUsuarios);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 590, 120));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TITULOUSUARIOS.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 310, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12345.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Usuarios", new javax.swing.ImageIcon(getClass().getResource("/mas/Usuarioss.png")), jPanel1); // NOI18N

        jPanel7.setBackground(new java.awt.Color(0, 0, 51));
        jPanel7.setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TITULOaCUMULADOR.png"))); // NOI18N
        jPanel7.add(jLabel15);
        jLabel15.setBounds(-20, 0, 330, 80);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e41a17bc530e920fe173955f5d5de442.png"))); // NOI18N
        jPanel7.add(jLabel13);
        jLabel13.setBounds(690, 0, 100, 130);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12345.png"))); // NOI18N
        jPanel7.add(jLabel5);
        jLabel5.setBounds(0, 0, 792, 660);

        jTabbedPane1.addTab("Acumulador", new javax.swing.ImageIcon(getClass().getResource("/mas/acumulador.png")), jPanel7); // NOI18N

        jPanel8.setBackground(new java.awt.Color(0, 0, 51));
        jPanel8.setLayout(null);

        jTable3.setBackground(new java.awt.Color(0, 0, 102));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Salario", "Dias trabajados", "Sueldo", "Descuentos", "Horas extras"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel8.add(jScrollPane3);
        jScrollPane3.setBounds(100, 180, 620, 100);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/Cacular.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/CacularPresed.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/CacularSelected.png"))); // NOI18N
        jPanel8.add(jButton2);
        jButton2.setBounds(630, 290, 107, 83);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e41a17bc530e920fe173955f5d5de442.png"))); // NOI18N
        jPanel8.add(jLabel17);
        jLabel17.setBounds(690, 0, 100, 130);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TITULO DE SALARIO.png"))); // NOI18N
        jPanel8.add(jLabel16);
        jLabel16.setBounds(-20, 0, 260, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12345.png"))); // NOI18N
        jPanel8.add(jLabel4);
        jLabel4.setBounds(0, 0, 792, 660);

        jTabbedPane1.addTab("Formato de Pago", new javax.swing.ImageIcon(getClass().getResource("/mas/Venta.png")), jPanel8); // NOI18N

        jPanel10.setBackground(new java.awt.Color(0, 0, 51));
        jPanel10.setLayout(null);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e41a17bc530e920fe173955f5d5de442.png"))); // NOI18N
        jPanel10.add(jLabel18);
        jLabel18.setBounds(690, 0, 100, 130);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuracion de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        lblNombre3.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre3.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre3.setText("Contraseña Actual");

        lblNombre4.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre4.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre4.setText("Nueva Contraseña");

        lblNombre5.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre5.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre5.setText("Confirmar contraseña");

        lblNombre6.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre6.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre6.setText("Nuevo Login");

        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/Aceptar Normal.png"))); // NOI18N
        btnAceptar.setToolTipText("");
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAceptar.setDefaultCapable(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.setFocusable(false);
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/Aceptar pressed.png"))); // NOI18N
        btnAceptar.setRequestFocusEnabled(false);
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/Aceptar Selected.png"))); // NOI18N
        btnAceptar.setVerifyInputWhenFocusTarget(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/Eliminar.png"))); // NOI18N
        btnEliminar.setToolTipText("");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setDefaultCapable(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/EliminarPressed.png"))); // NOI18N
        btnEliminar.setRequestFocusEnabled(false);
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones png/EliminarSeleted.png"))); // NOI18N
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNombre5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNombre6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNombre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre3)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblNombre6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre4)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre5))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar)
                            .addComponent(btnAceptar))
                        .addContainerGap())))
        );

        jPanel10.add(jPanel3);
        jPanel3.setBounds(140, 190, 560, 270);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CONGIF.png"))); // NOI18N
        jPanel10.add(jLabel11);
        jLabel11.setBounds(-20, 0, 360, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12345.png"))); // NOI18N
        jPanel10.add(jLabel6);
        jLabel6.setBounds(0, 0, 792, 660);

        jTabbedPane1.addTab("Configuración", new javax.swing.ImageIcon(getClass().getResource("/mas/Herramientas.png")), jPanel10); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
          ConsultasUsuarios con= new   ConsultasUsuarios ();
        con.insertar(txtId.getText(), txtUsuario.getText(), txtContraseña.getText(),this.cmbTipo.getSelectedItem().toString(),txtContraseña.getText());
       con.MostrarTabla(tablaUsuarios);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnAddEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpleadosActionPerformed
     ConsultasEmpleados cone= new   ConsultasEmpleados();
     cone.insertar(txtNombreEmpleado.getText(),txtApellidosEmpleado.getText(),txtCalleEmpleado.getText(),txtColoniaEmpleado.getText(),
     txtNumEmpleados.getText(),txtTelefonoEmpleados.getText(),txtMovilEmpleados.getText(),txtSalarioEmpleados.getText(),this.cmbCargoEmpleado.getSelectedItem().toString());
     actualizar();
       
      txtNombreEmpleado.setText("");
      txtApellidosEmpleado.setText("");
      txtCalleEmpleado.setText("");
      txtColoniaEmpleado.setText("");
      txtNumEmpleados.setText("");
      txtTelefonoEmpleados.setText("");
      txtMovilEmpleados.setText("");
      txtSalarioEmpleados.setText("");
    }//GEN-LAST:event_btnAddEmpleadosActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarActionPerformed

    private void txtNombreEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoKeyTyped
     String mayus=txtNombreEmpleado.getText();
     if(mayus.length()>0){ //si es mayor a 0 es que ya se esta escribiendo
      char letraprimera=mayus.charAt(0); //obtine la primera letra
      mayus=Character.toUpperCase(letraprimera)+mayus.substring(1,mayus.length());
       txtNombreEmpleado.setText(mayus);
            
     }
    }//GEN-LAST:event_txtNombreEmpleadoKeyTyped

    private void txtApellidosEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosEmpleadoKeyTyped
      String mayus=txtApellidosEmpleado.getText();
      if(mayus.length()>0){ //si es mayor a 0 es que ya se esta escribiendo
      char letraprimera=mayus.charAt(0); //obtine la primera letra
      mayus=Character.toUpperCase(letraprimera)+mayus.substring(1,mayus.length());
      txtApellidosEmpleado.setText(mayus);
      }
    }//GEN-LAST:event_txtApellidosEmpleadoKeyTyped

    private void txtCalleEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleEmpleadoKeyTyped
      String mayus=txtCalleEmpleado.getText();
      if(mayus.length()>0){ //si es mayor a 0 es que ya se esta escribiendo
      char letraprimera=mayus.charAt(0); //obtine la primera letra
      mayus=Character.toUpperCase(letraprimera)+mayus.substring(1,mayus.length());
      txtCalleEmpleado.setText(mayus);
      }
    }//GEN-LAST:event_txtCalleEmpleadoKeyTyped

    private void txtColoniaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColoniaEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColoniaEmpleadoActionPerformed

    private void txtColoniaEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColoniaEmpleadoKeyTyped
      String mayus=txtColoniaEmpleado.getText();
      if(mayus.length()>0){ //si es mayor a 0 es que ya se esta escribiendo
      char letraprimera=mayus.charAt(0); //obtine la primera letra
      mayus=Character.toUpperCase(letraprimera)+mayus.substring(1,mayus.length());
      txtColoniaEmpleado.setText(mayus);
      }
    }//GEN-LAST:event_txtColoniaEmpleadoKeyTyped
    
    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
    ConsultasEmpleados cone= new   ConsultasEmpleados();
     cone.eliminarempleados(txtEliminar.getText());
     actualizar();
    
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void txtEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEliminarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEliminarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAddEmpleados;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JComboBox<String> cmbCargoEmpleado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblDomicilio1;
    private javax.swing.JLabel lblDomicilio2;
    private javax.swing.JLabel lblDomicilio3;
    private javax.swing.JLabel lblDomicilio4;
    private javax.swing.JLabel lblDomicilio5;
    private javax.swing.JLabel lblDomicilio6;
    private javax.swing.JLabel lblDomicilio7;
    private javax.swing.JLabel lblDomicilio8;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JLabel lblNombre7;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono2;
    private javax.swing.JLabel lblTelefono3;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtApellidosEmpleado;
    private javax.swing.JTextField txtCalleEmpleado;
    private javax.swing.JTextField txtColoniaEmpleado;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMovilEmpleados;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNumEmpleados;
    private javax.swing.JTextField txtSalarioEmpleados;
    private javax.swing.JTextField txtTelefonoEmpleados;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void actualizar() {
        cone.MostrarTablaEmpleados(TablaEmpleados);
    }
}
